# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f53c4d3923b8073397370bc6314adcd4f925549af7e28220d2bb1aa15d87c6b1d8ec481d6f48fb8b32cfd63a9057909e1a665b70f5cd7326d236c3f39a47e87c

test:
  secret_key_base: 6d703a15210277c9f07b3057096803833e0aa02a2ceaee1a9027ab76495fd3c8ec8a78e9671c8420246430301bd271601c92a6596d27404f651d2570cb647f0a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
